[versions]
kotlin = "1.8.0"
kotlinDokka = "1.7.20"

androidGradleStable = "7.3.1"
androidGradle = "7.4.0-rc01"
androidNavigation = "2.5.3"

mokoMobileMultiplatform = "0.14.1"
mokoResources = "0.20.1"
mokoKswift = "0.6.1"

buildkonfig = "0.12.0"
sqldelight = "1.5.4"
googleServices = "4.3.10"
nexusPublish = "1.1.0"
crashlytics = "2.8.1"

mersey-plugins = "1.0.5"

[libraries]
# Kotlin
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "kotlinDokka" }

# Android
android-gradle-stable = { module = "com.android.tools.build:gradle", version.ref = "androidGradleStable" }
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradle" }
android-gradleApi = { module = "com.android.tools.build:gradle-api", version.ref = "androidGradle" }
android-navigation-safeArgs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidNavigation" }

# Other
buildkonfig = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version.ref = "buildkonfig" }
sqldelight = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqldelight" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
nexusPublish = { module = "io.github.gradle-nexus:publish-plugin", version.ref= "nexusPublish" }
crashlytics = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics" }

# Moko
moko-mobileMultiplatform = { module = "dev.icerock:mobile-multiplatform", version.ref = "mokoMobileMultiplatform" }
moko-resourcesGenerator = { module = "dev.icerock.moko:resources-generator", version.ref = "mokoResources" }
moko-kswift = { module = "dev.icerock.moko:kswift-gradle-plugin", version.ref = "mokoKswift" }

# Mersey
mersey-gradlePlugins = { module = "io.github.merseyside:plugins", version.ref = "mersey-plugins" }