[versions]
ktor = "2.2.1"
sqldelight = "1.5.4"

[libraries]
sqldelight = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqldelight" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

[bundles]
