[versions]
ktor = "2.3.6"
sqldelight = "2.0.0"

[libraries]
sqldelight = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

[bundles]
