[versions]
kotlin = "1.6.20"
versionChecker = "0.42.0"
mokoKswift = "0.4.0"
swiftPackage = "2.0.3"
pluginPublish = "0.15.0"
merseyPlugins = "1.0.4"

[plugins]
android-library = { id = "com.android.library" }
android-application = { id = "com.android.application" }
android-navigation-args = { id = "androidx.navigation.safeargs.kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform" }
kotlin-kapt = { id = "kotlin-kapt" }
kotlin-serialization = { id = "kotlinx-serialization" }
kotlin-android = { id = "kotlin-android" }
signing = { id = "signing" }
mavenPublish = { id = "maven-publish" }
nexusConfig = { id = "nexus-config" }
sqldelight = { id = "com.squareup.sqldelight" }

moko-multiplatform = { id = "dev.icerock.mobile.multiplatform" }
moko-kswift = { id = "dev.icerock.moko.kswift", version.ref = "mokoKswift" }
moko-resources = { id = "dev.icerock.mobile.multiplatform-resources" }

#Mersey plugins
mersey-android-convention = { id = "io.github.merseyside.android-convention", version.ref = "merseyPlugins" }
mersey-kotlin-convention = { id = "io.github.merseyside.kotlin-convention", version.ref = "merseyPlugins" }

cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }

versionChecker = { id = "com.github.ben-manes.versions", version.ref = "versionChecker" }
swiftPackage = { id = "com.chromaticnoise.multiplatform-swiftpackage", version.ref = "swiftPackage" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref= "pluginPublish" }