[versions]
#kotlin
kotlin = "1.5.30"
serialization = "1.3.0-RC"
versionChecker = "0.39.0"

#Mersey libs
time = "1.0.2"

[libraries]
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

#Mersey libs
merseyLib-time = { module = "io.github.merseyside:time", version.ref = "time" }

[plugins]
versionChecker = { id = "com.github.ben-manes.versions", version.ref = "versionChecker"}

