[versions]
kotlin = "1.5.31"
serialization = "1.3.0"

appCompat = "1.3.1"
activity = "1.3.1"
annotation = "1.2.0-alpha01"
material = "1.4.0"
coroutines = "1.5.2"
fragment = "1.3.6"
constraintLayout = "2.0.3"
lifecycle = "2.3.1"
cardView = "1.0.0"
recyclerView = "1.2.1"
dagger = "2.38.1"
navigation = "2.3.5"
paging = "3.0.1"
billing = "4.0.0"
publisher = "v3-rev20210728-1.32.1"
auth = "1.0.0"
firebaseFirestore = "23.0.3"
playCore = "1.10.1"
keyboard = "3.0.0-RC3"
gson = "2.8.8"
worker = "2.6.0"
room = "2.3.0"
rxjava2 = "2.2.20"
coil = "1.3.2"
typedDataStore = "1.0.0"
location = "18.0.0"
ktor = "1.6.2"
koin = "3.1.2"
sqldelight = "1.5.0"
moko-mvvm = "0.11.0"
bouncyCastle = "1.65"
phoneValidator = "8.12.26"
zip4j = "2.9.0"

firebaseMessaging = "22.0.0"

merseyLib = "1.5.5"
kmmLibrary = "1.4.3"
filemanager = "1.0.7"
firestoreCoroutines = "1.0.3"

[libraries]
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
activityKtx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
material = { module = "com.google.android.material:material", version.ref = "material" }
fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
recyclerView = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerView" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
lifecycleViewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycleViewModelSavedState = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
lifecycleLiveDataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
cardView = { module = "androidx.cardview:cardview", version.ref = "cardView" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
rxjava2 = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava2" }
paging = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
playCore = { module = "com.google.android.play:core", version.ref = "playCore" }
billing = { module = "com.android.billingclient:billing-ktx", version.ref = "billing" }
publisher = { module = "com.google.apis:google-api-services-androidpublisher", version.ref = "publisher" }
firebaseFirestore = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebaseFirestore" }
oauth2 = { module = "com.google.auth:google-auth-library-oauth2-http", version.ref = "auth" }
room = { module = "androidx.room:room-runtime", version.ref = "room" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
daggerCompiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
navigation = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigationUi = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
keyboard = { module = "net.yslibrary.keyboardvisibilityevent:keyboardvisibilityevent", version.ref = "keyboard" }
worker = { module = "androidx.work:work-runtime-ktx", version.ref = "worker" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
typedDataStore = { module = "androidx.datastore:datastore", version.ref = "typedDataStore" }
location = { module = "com.google.android.gms:play-services-location", version.ref = "location" }
koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }
sqldelight = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqldelight" }
bouncyCastle = { module = "org.bouncycastle:bcpkix-jdk15on", version.ref = "bouncyCastle" }
phoneValidator = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "phoneValidator" }
zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }

ktor = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }

moko-mvvm-databinding = { module = "dev.icerock.moko:mvvm-databinding", version.ref = "moko-mvvm" }
moko-mvvm-viewbinding = { module = "dev.icerock.moko:mvvm-viewbinding", version.ref = "moko-mvvm" }
moko-mvvm-livedata-material = { module = "dev.icerock.moko:mvvm-livedata-material", version.ref = "moko-mvvm" }

#Mersey libs
merseyLib-archy = { module = "com.github.Merseyside.mersey-android-library:archy", version.ref="merseyLib" }
merseyLib-adapters = { module = "com.github.Merseyside.mersey-android-library:adapters", version.ref="merseyLib" }
merseyLib-animators = { module = "com.github.Merseyside.mersey-android-library:animators", version.ref="merseyLib" }
merseyLib-utils = { module = "com.github.Merseyside.mersey-android-library:utils", version.ref="merseyLib" }
merseyLib-filemanager = { module = "com.github.Merseyside:android-filemanager", version.ref="filemanager" }
merseyLib-firestoreCoroutines = { module = "com.github.Merseyside:firestore-coroutines", version.ref="firestoreCoroutines" }

merseyLib-archyAndroid = { module = "io.github.merseyside:archy-android", version.ref = "kmmLibrary" }

[bundles]
lifecycle = ["lifecycleViewModel", "lifecycleViewModelSavedState", "lifecycleLiveDataKtx"]
navigation = ["navigation", "navigationUi"]
room = ["room", "roomKtx"]
merseyLibs = ["merseyLib-archy", "merseyLib-adapters", "merseyLib-animators", "merseyLib-utils"]
moko-mvvm = ["moko-mvvm-databinding", "moko-mvvm-viewbinding", "moko-mvvm-livedata-material"]
ktor = ["ktor", "ktor-okhttp"]